IG-42 added docker image checks

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -10,60 +10,60 @@ concurrency:
   group: ${{ github.ref }}-ci-workflow
 
 jobs:
-  # build:
-  #   runs-on: ubuntu-latest
-  #   continue-on-error: false
-  #   timeout-minutes: 5
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
+  build:
+    runs-on: ubuntu-latest
+    continue-on-error: false
+    timeout-minutes: 5
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-  #     - name: Setup Node.js
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: "14"
-  #         cache: 'npm'
-  #         cache-dependency-path: frontend/package-lock.json
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "14"
+          cache: 'npm'
+          cache-dependency-path: frontend/package-lock.json
 
-  #     - name: Cache node modules
-  #       uses: actions/cache@v2
-  #       with:
-  #         path: |
-  #           frontend
-  #       key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+      - name: Cache node modules
+        uses: actions/cache@v2
+        with:
+          path: |
+            frontend
+        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
-  #     - name: Install Dependencies
-  #       run: |
-  #         cd frontend
-  #         npm ci
+      - name: Install Dependencies
+        run: |
+          cd frontend
+          npm ci
 
-  #     - name: Start Server
-  #       run: |
-  #         cd frontend
-  #         npm run serve & 
-  #         serve_pid=$! 
+      - name: Start Server
+        run: |
+          cd frontend
+          npm run serve & 
+          serve_pid=$! 
 
-  #     - name: Wait for the Vue.js app to start
-  #       run: |
-  #         for _ in {1..18}; do
-  #           if curl -I http://localhost:8080 -s -f -o /dev/null; then
-  #             echo "Vue.js app is running."
-  #             exit 0  # The app is running, exit the loop
-  #           fi
-  #           sleep 10
-  #         done
-  #         echo "Vue.js app didn't start in time or encountered an error."
-  #         exit 1
+      - name: Wait for the Vue.js app to start
+        run: |
+          for _ in {1..18}; do
+            if curl -I http://localhost:8080 -s -f -o /dev/null; then
+              echo "Vue.js app is running."
+              exit 0  # The app is running, exit the loop
+            fi
+            sleep 10
+          done
+          echo "Vue.js app didn't start in time or encountered an error."
+          exit 1
 
-  #     - name: Stop the Vue.js app
-  #       run: |
-  #         kill $serve_pid
+      - name: Stop the Vue.js app
+        run: |
+          kill $serve_pid
   
-  # Backend
   fetch-merge-reference:
     runs-on: ubuntu-latest
     continue-on-error: false
     timeout-minutes: 5
+    needs: build
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -109,12 +109,33 @@ jobs:
           echo "::set-output name=testing_branch::$testing_branch"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  test:
+  
+  test-docker-image:
     runs-on: ubuntu-latest
     continue-on-error: false
     timeout-minutes: 15
     needs: create-and-merge-testing-branch
+    steps:
+      - name: Set up Docker
+        uses: docker/setup-action@v2
+
+      - name: Build Production Docker image
+        run: docker build -t production -f backend/production_backend/Dockerfile .
+
+      - name: Run Production Docker container
+        run: docker run production
+
+      - name: Build Test Docker image
+        run: docker build -t test -f backend/test_backend/Dockerfile .
+
+      - name: Run Test Docker container
+        run: docker run test
+
+  test-functions:
+    runs-on: ubuntu-latest
+    continue-on-error: false
+    timeout-minutes: 15
+    needs: test-docker-image
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
@@ -158,7 +179,7 @@ jobs:
   delete-testing-branch:
     runs-on: ubuntu-latest
     continue-on-error: false
-    needs: test
+    needs: test-functions
     if: always()
     steps:
       - name: Checkout code
